# Generated by Django 5.1.4 on 2024-12-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LnDiccionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LnPatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron', models.CharField(max_length=255)),
                ('consulta_sql', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Piso', 'Piso'), ('Casa', 'Casa'), ('Chalet', 'Chalet')], max_length=50)),
                ('zona', models.CharField(max_length=255)),
                ('ndormitorios', models.IntegerField()),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('garaje', models.BooleanField(default=False)),
            ],
        ),
    ]
