# Generated by Django 5.1.4 on 2024-12-17 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lindavista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lnpatron',
            old_name='consulta_sql',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='lnpatron',
            name='patron',
        ),
        migrations.AddField(
            model_name='lnpatron',
            name='codigo',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lnpatron',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
