# Generated by Django 5.1.4 on 2024-12-21 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lindavista', '0003_remove_lnpatron_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnpatron',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='lndiccionario',
            name='descripcion',
            field=models.TextField(default='Descripción por defecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lnpatron',
            name='consulta_sql',
            field=models.CharField(default='Descripción por defecto', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lnpatron',
            name='patron',
            field=models.CharField(default=datetime.datetime(2024, 12, 21, 6, 6, 35, 465038, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lndiccionario',
            name='palabra',
            field=models.CharField(max_length=100),
        ),
    ]
