# Generated by Django 5.1.4 on 2024-12-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lindavista', '0004_remove_lnpatron_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='LnDiccionario',
        ),
        migrations.DeleteModel(
            name='LnPatron',
        ),
        migrations.DeleteModel(
            name='Vivienda',
        ),
    ]
