# Generated by Django 5.1.4 on 2024-12-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lindavista', '0005_propiedad_delete_lndiccionario_delete_lnpatron_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(choices=[('departamento', 'Departamento'), ('casa', 'Casa'), ('oficina', 'Oficina')], max_length=20),
        ),
    ]
